# Generated by Django 3.2.6 on 2021-08-09 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sender', 'receiver', 'message', 'subject')},
        ),
        migrations.CreateModel(
            name='MessageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='message.message')),
                ('read_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seen_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
